const actions = {
  FETCH_NOTES: "FETCH_NOTES",
  SET_CUSTOMERS: "SET_CUSTOMERS",
  FETCH_CUSTOMER_ERROR: "FETCH_CUSTOMER_ERROR",
  UPDATE_MAP_DATA: "UPDATE_MAP_DATA",
  UPDATE_PAGECOUNT: "UPDATE_PAGECOUNT",
  CREATE_NEW_NOTE: "CREATE_NEW_NOTE",
  NOTES_CREATED: "NOTES_CREATED",
  NOTES_CREATION_ERROR: "NOTES_CREATION_ERROR",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMERS_DELETE: "CUSTOMERS_DELETE",
  UPLOAD_AVATAR: "UPLOAD_AVATAR",
};

export default actions;
